library(caret)
new_names <- c("ZIP.Code", "Personal.Loan", "Securities.Account", "CD.Account")
names(universal) <- new_names
install.packages("caret")
library(caret)
install.packages("ISLR")
library(ISLR)
library(dplyr)
install.packages("dplyr")
install.packages(c("caret", "class"))
library(caret)
library(class)
install.packages("caret")
library(caret)
install.packages("FNN")
library(FNN)
install.packages("gmodels")
library("gmodels")
levels(train.norm.df$`Personal Loan`)
levels(valid.norm.df$`Personal Loan`)
valid.norm.df$`Personal Loan` <- factor(valid.norm.df$`Personal Loan`, levels = levels(train.norm.df$`Personal Loan`))
knn.pred_numeric <- as.numeric(knn.pred)
actual_values_numeric <- as.numeric(valid.norm.df$`Personal Loan`)
unique_levels_knn_pred <- levels(knn.pred)
unique_levels_reference <- levels(valid.norm.df$`Personal Loan`)
valid.norm.df$`Personal Loan` <- factor(valid.norm.df$`Personal Loan`, levels = unique_levels_knn_pred
